insert into tariff_mobile values (1, 'some text', 30, 'Profitable', 450, 500, 500);
insert into tariff_mobile values (2, 'some text2', 10, 'Simple', 350, 300, 300);
insert into tariff_home values (1, 'The best packet', 40, 'Profitable', 500);
insert into contacts_impl values (1, 'Point name', 'Russia, Moscow, Novoslobodskaya street, 15', '78-45-35', 'mon-fri');
insert into vacancy_impl values (2, 'Operator', 'good work');
insert into faq_impl values (1, 'Yes, call us. All information you can found in page "Contacts"', 'Can I switch my tariff without pay?');
insert into faq_impl values (2, 'Yes, visit page named "Work"', 'Can I supply my resume to you to get work?');
insert into modem values (1, 'Description', 'https://items.s1.citilink.ru/1114602_v01_b.jpg', 'Modem', 1000, 'Short description','Specifications');
insert into modem values (2, 'Description', 'https://shop.mts.ru/upload/iblock/e07/mts_konnekt_4g_lte_wi_fi_router_1.jpg/resize/125x170/', 'Router', 2000, 'Short description', 'Specifications');
insert into tech values (1, 'Description', 'https://shop.mts.ru/upload/iblock/95d/planshet_apple_ipad_10_2_2019_32gb_wi_fi_cellular_seryj_kosmos.jpg', 'Tablet', 40000, 'Short description', 'Specifications');